spring:
  config:
    name: zuul
  application:
    name: zuul

server:
  tomcat:
    basedir: /tmp/zuul/tomcat
    accesslog:
      directory: /tmp/zuul/accesslog
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
  port: 9080

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    level:
      org.springframework.cloud: 'INFO'

security:
  basic:
    enabled: false
  user:
    name: testuser
    password: testpassword

eureka:
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: true

zuul:
  host:
    maxTotalConnections: 15
    maxPerRouteConnections: 3
  ignoredServices: '**'
  routes:
    testapp1: /testapp1/**